# Branch Protection Rules Configuration

branches:
  main:
    # Require pull request reviews
    required_reviews:
      required_approving_review_count: 1
    
    # Required status checks
    required_status_checks:
      strict: true
      checks:
        - "Validate PR"
    
    # Branch restrictions
    enforce_admins: true
    allow_force_pushes: false
    allow_deletions: false